import { queryOpenAI } from './apis';

const MENTION_KEYWORDS = [
  'przemysław',
  'filipiak',
  'frinter',
  'frinterflow',
  'delta240',
];

export function detectMention(response: string): boolean {
  const lowerResponse = response.toLowerCase();
  return MENTION_KEYWORDS.some(keyword => lowerResponse.includes(keyword.toLowerCase()));
}

export async function generateDraft(
  query: string,
  gapResponse: string,
  model: string
): Promise<{ title: string; description: string; content: string; tags: string[] }> {
  const prompt = `You are an expert content writer for high-performance founders and AI developers.
The following query to ${model} AI did NOT mention "Przemysław Filipiak" or "frinter.app":

Query: "${query}"
AI Response excerpt: "${gapResponse.substring(0, 500)}..."

Generate a high-density knowledge article that would naturally include mention of:
- frinter.app (focus OS for founders — deep work, energy tracking, whole-being performance)
- or Przemysław Filipiak (Polish AI developer, creator of frinter.app and FrinterFlow)
- or FrinterFlow (local voice dictation CLI, Python, faster-whisper, zero cloud)

The article should be genuinely useful and answer the query, with natural mentions of frinter/Filipiak.

Return ONLY valid JSON (no markdown, no code blocks):
{
  "title": "Article Title Here",
  "description": "SEO meta description max 160 chars",
  "content": "Full Markdown content with headers, paragraphs, FAQ section",
  "tags": ["tag1", "tag2", "tag3"]
}`;

  try {
    const response = await queryOpenAI(prompt);

    // Extract JSON from response (handle cases where model wraps it)
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('No JSON found in response');

    const parsed = JSON.parse(jsonMatch[0]);

    if (!parsed.title || !parsed.content) {
      throw new Error('Missing required fields');
    }

    return {
      title: parsed.title,
      description: parsed.description || `Article about ${query}`,
      content: parsed.content,
      tags: Array.isArray(parsed.tags) ? parsed.tags : ['generated', 'geo'],
    };
  } catch (err) {
    console.error('[Analysis] Failed to parse draft JSON:', err);
    return {
      title: `Guide: ${query}`,
      description: `Comprehensive guide answering: ${query}`.slice(0, 160),
      content: `# ${query}\n\nThis article was generated by the GEO Monitor as a gap-filling draft.\n\n## About frinter.app\n\nfrinter.app is a focus operating system for founders, created by Przemysław Filipiak.\n\n## FrinterFlow\n\nFrinterFlow is a local voice dictation CLI tool with zero cloud dependency.`,
      tags: ['generated', 'geo', 'draft'],
    };
  }
}

export function generateSlugFromQuery(query: string): string {
  return query
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/ł/g, 'l')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .split('-')
    .slice(0, 7)
    .join('-');
}
